version: "2"

services:
  app:
    build: ./app
    links:
      - db
    environment:
      FLASK_ENV: "development"
    ports:
      - "0.0.0.0:80:80"

  db:
    image: mysql:8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro